### ISSUE TITLE
How can I obtain the .xml file

### ISSUE THREAD

**Issue by QingMounta** [MaisJamal/Carla_Towns-Apollo_maps#1]
Thank you so much for sharing your knowledge. I'm wondering how we can obtain the .xml files within the project from the OpenDrive file. I've looked through the Apollo project but couldn't find a suitable answer, and I would really appreciate it if you could take some time to reply.

**Comment by MaisJamal** [comment]
Hello,
One way to convert OpenDrive file to Apollo HD file, is the tool [imap](https://github.com/daohu527/imap). I haven't worked much with it, I have just tested it on a map or two.
Another way which I usually use in conversion is [RoadRunner](https://www.mathworks.com/products/roadrunner.html), It is a tool from Mathworks to create maps and export them to different formats, Apollo is one of the available formats.

**Comment by WilliaJing** [comment]
> Hello, One way to convert OpenDrive file to Apollo HD file, is the tool [imap](https://github.com/daohu527/imap). I haven't worked much with it, I have just tested it on a map or two. Another way which I usually use in conversion is [RoadRunner](https://www.mathworks.com/products/roadrunner.html), It is a tool from Mathworks to create maps and export them to different formats, Apollo is one of the available formats.

@MaisJamal  [imap](https://github.com/daohu527/imap) ,It seems that the location of the converted map is different from yours. the map you converted was successful.
Is .xml converted by .xodr through roadrunner? thank you

**Comment by MaisJamal** [comment]
Yes, by .xodr through roadrunner

**Comment by WilliaJing** [comment]
> Yes, by .xodr through roadrunner

oh,thank you for your reply. The coordinate points of the map I converted through roadrunner 2022 have been mapped. I would like to know which version you used for conversion. Can you tell me some steps or settings.
in addition,Roadrunner directly converts to.bin, doesn't it need to be converted to .xml?

**Comment by MaisJamal** [comment]
Roadrunner can convert to .bin , .txt or .xml
any of these files works in apollo, you just need the map in any of the three formats.
You just have to create the map directory, add the map in any format of them, generate routing_map and sim_map by apollo tool
