### ISSUE TITLE
carla地图制作成apollo地图

### ISSUE THREAD

**Issue by fpeanut** [MaisJamal/Carla_Towns-Apollo_maps#2]
你好，请问将carla地图转换车apollo的地图的方法能否分享一下！

**Comment by MaisJamal** [comment]
Hello, 
I have not converted maps of Carla to Apollo HD format directly.  What I did instead, I searched on the internet for Carla's available maps in Apollo format, extracted them from docker containers and put them all in one repository.
If you need a direct way for conversion, I can suggest [imap](https://github.com/daohu527/imap) which allow you to convert maps in OpenDrive format to apollo HD format. All CarlaTowns are available in OpenDrive formats.
