### ISSUE TITLE
sorry for my big confusion

### ISSUE THREAD

**Issue by 2019211753** [MaisJamal/Carla_Towns-Apollo_maps#3]
could please tell me what does the "copy to it base_map.xml" mean? I can't understand maybe because my native language is not english. Copy what to it? The directory?

**Comment by MaisJamal** [comment]
Hello,
I meant to move the file base_map.xml to the map directory which you have create in apollo/modules/map/data.
All the three base_map files: .txt , .xml , .bin denote the same map in different format. You can use any one of them to generate the needed extra files: routing_map and sim_map. You can check this [link](https://github.com/ApolloAuto/apollo/tree/master/modules/map/data) for further information regarding the map format in Apollo.
